### PR TITLE
feat(common-utils): adds ping to common utils feature

### PR DESCRIPTION
**Pull request by gpascual2**
Adds *ping* package (from iputils) to common-utils to complement the set of networking tools of this feature.

### CODE REVIEW

**Comment by gpascual2** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by bamurtaugh** [comment]
Thanks for opening @gpascual2! As a heads up, we're discussing splitting up the common Feature: https://github.com/devcontainers/features/issues/67.

**Comment by samruddhikhandale** [comment]
Hi @gpascual2, could you sync this `PR` with main? 
https://github.com/devcontainers/features/pull/245 added more base images for PRs to test against. It would be nice to validate.

**Comment by samruddhikhandale** [comment]
Closing as stale. Feel free to reopen if needed, thanks!

**Pull request closed without merging**
