### PR TITLE
Add a feature that installs dependencies from an `Aptfile.dev` file

### PR DESCRIPTION
**Pull request by viktorianer**
### Description:

This PR introduces a new feature for installing apt dependencies in the DevContainer environment using an `Aptfile.dev` file. The feature simplifies the process of managing apt packages required for the development environment by specifying them in a file and automating the installation during the container setup process.

#### Usage:

To use the feature, include the following in your `devcontainer.json`:

```json
{
  "features": {
    "ghcr.io/devcontainers/features/apt:1": {
      "devFile": "../Aptfile.dev"
    }
  }
}
```

Example `Aptfile.dev`

```bash
# Video thumbnails
ffmpeg
libvips

# PDF thumbnails
poppler-utils

# PostgreSQL
libpq-dev
postgresql-client
```

### Additional Information:

Based on the approach found in https://github.com/heroku/heroku-buildpack-apt and https://docs.digitalocean.com/products/app-platform/reference/buildpacks/aptfile/.

### CODE REVIEW

**Comment by viktorianer** [comment]
@microsoft-github-policy-service agree

**Comment by viktorianer** [comment]
Thank you for the feedback. I have reviewed those documents and understand that this repository focuses on improvements and bug fixes for the existing set of maintained Features.

I completely understand if adding a new Feature doesn’t align with the current goals of this repository. 

If this contribution is not considered for merging, I’m happy to proceed by maintaining this Feature in a separate repository.

Thank you for your time and consideration!

**Comment by samruddhikhandale** [comment]
Hi 👋 

As @eitsupi already mentioned, we appreciate your Feature contribution, however, the `devcontainers/features` repo only accepts improvements and bug fixes for the [current set of maintained Features](https://github.com/devcontainers/features/blob/main/src). 

However, we would appreciate if you could add this Feature in a separate repository of your control. The [devcontainers/feature-starter](https://github.com/devcontainers/feature-starter) repo has more guidance on self authoring them.

Once you've self authored and if you'd like to share it with the community, we'd recommend [adding it to the index](https://github.com/devcontainers/feature-starter#adding-features-to-the-index). It will make them visible in our [supporting tools](https://containers.dev/supporting) (like https://containers.dev/templates, Dev Containers Extension, GitHub Codespaces etc).

Feel free to ask any questions/queries along the way, feedbacks are welcome too!

**Comment by viktorianer** [comment]
If anyone needs or wants to use this feature, you can now find it here: [https://github.com/viktorianer/devcontainer-features](https://github.com/viktorianer/devcontainer-features).  

I’d also love to see this merged so it gets listed: [https://github.com/devcontainers/devcontainers.github.io/pull/514](https://github.com/devcontainers/devcontainers.github.io/pull/514).  

Thanks a lot!

**Pull request closed without merging**
