### PR TITLE
Fix: Handle case where Python version is already installed (#222)

### PR DESCRIPTION
**Pull request by gvatsal60**
- Fix: Handle case where Python version is already installed (#617)

### CODE REVIEW

**Comment by gvatsal60** [comment]
Hi @samruddhikhandale 
Could you check out the pull request when you have a moment?

**Comment by samruddhikhandale** [comment]
@gvatsal60 The code is intentionally in place. Why would you want to remove `exit 1`? If the version still exists, why not pass `none` or another version?

**Comment by gvatsal60** [comment]
> @gvatsal60 The code is intentionally in place. Why would you want to remove `exit 1`? If the version still exists, why not pass `none` or another version?

I am looking into it. Will update the PR soon.

**Comment by gvatsal60** [comment]
@samruddhikhandale I have updated the PR. Please have a look...

**Review by samruddhikhandale — APPROVED** [review]
This change make sense to me, let's merge provided the tests are green. Thanks!

**Comment by rubensa** [comment]
@samruddhikhandale Shouldn't this have generated a [version](https://github.com/devcontainers/features/blob/main/src/python/devcontainer-feature.json#L3C3-L3C22) update?

I thought that any feature change merged to **main** should have its corresponding version update.

NOTE:  I just came here trying to check if [this PR](https://github.com/devcontainers/features/pull/1142) made the GitHub tags work again but, as the version was not updated, no luck to check...

**Comment by gvatsal60** [comment]
Hi @rubensa,

I realized I forgot to update the version in the previous PR. I've submitted a new one to address this: [#1148](https://github.com/devcontainers/features/pull/1148).

I’ll also look into solutions to prevent version update oversights in the future.

Thank you!

**Pull request merged**
