### PR TITLE
Update Oryx feature to install if a newer version of .NET is present

### PR DESCRIPTION
**Pull request by seesharprun**
Oryx fails to install if a newer version of .NET is present.

I suspect this is due to a missing `--framework` argument.

I also took this opportunity to spell out the full name of other `dotnet build` and `dotnet publish` arguments to make it easier to debug for the person that comes next.

### CODE REVIEW

**Comment by seesharprun** [comment]
This PR is an attempt to resolve devcontainers/images#855

**Comment by seesharprun** [comment]
There is still some more work that needs to be done. Even on my local machine, I can't build Oryx from source if I have both .NET 7 and .NET 8 installed.

**Comment by seesharprun** [comment]
It looks like the feature runs `dotnet --version` which will always return the latest version of .NET.

Instead it should check `dotnet --list-sdks` to see if .NET 7 is included in the list.

**Comment by seesharprun** [comment]
A little more investigating has uncovered that some of the assemblies (Ex: Microsoft.NET.Sdk.Razor/source-generators/Microsoft.NET.Sdk.Razor.SourceGenerators.dll) will always use the latest .NET version if multiple versions are enabled.

I looked around on GitHub and found a couple of example issues where the .NET team says this is intentional behavior. They don't want someone to "freeze" on an old dependency and lock it in for years after moving on to newer versions of .NET.

**Comment by samruddhikhandale** [comment]
Feel free to close this in favor of https://github.com/devcontainers/features/pull/825 which should unblock  https://github.com/devcontainers/images/pull/855

**Pull request closed without merging**
