### PR TITLE
Avoid unexpected shell expansion

### PR DESCRIPTION
**Pull request by shikanime**
Some variables may contain symbols such as wildcards, which can be expanded by other shell interpreters such as ZSH.

Fix: https://github.com/devcontainers/features/issues/569

### CODE REVIEW

**Comment by shikanime** [comment]
@microsoft-github-policy-service agree

**Review by samruddhikhandale — CHANGES_REQUESTED** [review]
Looks great, thanks for taking the time to contribute this PR.
Left a minor comment.

**Comment by samruddhikhandale** [comment]
> ERROR: failed to solve: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/local/bin/git: no space left on device

Looks like the tests are failing due to ^ disk space issues , see https://github.com/devcontainers/features/actions/runs/5813161318/job/15762628752?pr=645#step:4:3293

@shikanime can you help remove the "install_node_on_universal_image" scenario? https://github.com/devcontainers/features/blob/5128a41391094f5423c781c8ccd4fe6d4ae094fc/test/node/scenarios.json#L40-L48 

The universal image is ~ 12.5 GB, we shouldn't be using such a big image which will result in slow (local) test runs. Also, it would help fix the disk space issue in the runners.

I'll create an issue for myself to re-add a (slim) test scenario as a replacement.

**Comment by samruddhikhandale** [comment]
Opened https://github.com/devcontainers/features/issues/646

**Review by samruddhikhandale — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
